# Generated by Django 4.2 on 2023-04-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_autos_delete_animales_delete_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('contenido', models.CharField(max_length=1000)),
                ('descripcion_contenido', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='autos',
        ),
    ]
