# Generated by Django 4.2 on 2023-05-29 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='usuario',
            new_name='user',
        ),
    ]
